### ISSUE TITLE
衬线字体和中英文切换的建议

### ISSUE THREAD

**Issue by tangjyan** [RayeRen/acad-homepage.github.io#10]
1、学术期刊中一般正文都用衬线字体，如 Times New Roman, Georgia，Latin Modern. 看着更学术一点，希望模板可以提供字体选择。
2、希望可以提供中英文切换，就像Github的Readme.md一样。

**Comment by S-Kee** [comment]
基本解决
# 衬线字体
可以分别在各个字体设置中改，但是太麻烦，可以直接在`_sass`-`_variables.scss`中把非衬线字体的后面都改为衬线字体，Georgia比较好看。
$serif: Georgia, erif;

# 中英文切换
可以再建一个完全一样的仓库叫zh-cn，改为中文内容，这样访问https://[name].github.io/zh-cn 就可以很跳转了，然后将原模板网页中左上角没用的”[Homepage]“改为中英文切换，在`_includes`-`masthead.html`中改。有几个坑
- 无法再fork，只能新建再设置
- 中文锚点不起作用，可以自定义新锚点
- [Homepage]在移动端会隐藏，找到css取消隐藏
- 中英文切换会新建标签页，css中加self属性
- masthead.html中的navigation.yml url要加/zh-cn前缀
