### ISSUE TITLE
how to add zhihu link?

### ISSUE THREAD

**Issue by kunkun0w0** [RayeRen/acad-homepage.github.io#12]

**Comment by Koohoko** [comment]
To add Zhihu link in author profile ([Demo](https://koohoko.github.io)), please just:
1. Change your `/_includes/author-profile.html` with [my version](https://github.com/Koohoko/Koohoko.github.io/blob/a427daca5ec712c2c78b6349f4d301b2b8f17ec8/_includes/author-profile.html).
2. Add your zhihu account name in `/_config.yml`, like [here](https://github.com/Koohoko/Koohoko.github.io/blob/a427daca5ec712c2c78b6349f4d301b2b8f17ec8/_config.yml#L73).

**Comment by Koohoko** [comment]
> No description provided.

To add Zhihu link in author profile ([Demo](https://koohoko.github.io)), please just:
1. Change your `/_includes/author-profile.html` with [my version](https://github.com/Koohoko/Koohoko.github.io/blob/a427daca5ec712c2c78b6349f4d301b2b8f17ec8/_includes/author-profile.html).
2. Add your zhihu account name in `/_config.yml`, like [here](https://github.com/Koohoko/Koohoko.github.io/blob/a427daca5ec712c2c78b6349f4d301b2b8f17ec8/_config.yml#L73).
