### ISSUE TITLE
i got problem in add automatic update google scholar citation  function.

### ISSUE THREAD

**Issue by yangxinsci1993** [RayeRen/acad-homepage.github.io#14]
I tried to add my google scholar citation using the format you left but the citation always shows the wrong number, can you help to figure it out? Thank you so much for your help!

**Comment by yangxinsci1993** [comment]
Problem solved! Thank you! I forget to change the repository address...

**Comment by YuMJie** [comment]
![image](https://user-images.githubusercontent.com/64304120/222172138-fe404671-a1be-462f-979d-3574ea7184d4.png)


> Problem solved! Thank you! I forget to change the repository address...

did you get this problem? could you tell me how to solve it?
