### ISSUE TITLE
新人遇到bug -- Internal Server Error

### ISSUE THREAD

**Issue by taokz** [RayeRen/acad-homepage.github.io#23]
本地调试的时候，http://127.0.0.1:4000， 出现

Internal Server Error
undefined method `key?' for nil:NilClass return unless @mime_types_charset.key?(typ) ^^^^^
WEBrick/1.8.1 (Ruby/3.1.3/2022-11-24) at 127.0.0.1:4000

terminal上显示
ERROR NoMethodError: undefined method `key?' for nil:NilClass\n\n          return unless @mime_types_charset.key?(typ)\n                                           ^^^^^
	/Users/kai/.gem/ruby/3.1.3/gems/jekyll-3.9.3/lib/jekyll/commands/serve/servlet.rb:191:in `conditionally_inject_charset'
	/Users/kai/.gem/ruby/3.1.3/gems/jekyll-3.9.3/lib/jekyll/commands/serve/servlet.rb:176:in `do_GET'
	/Users/kai/.gem/ruby/3.1.3/gems/hawkins-2.0.5/lib/hawkins/servlet.rb:134:in `do_GET'
	/Users/kai/.gem/ruby/3.1.3/gems/webrick-1.8.1/lib/webrick/httpservlet/abstract.rb:105:in `service'
	/Users/kai/.gem/ruby/3.1.3/gems/webrick-1.8.1/lib/webrick/httpservlet/filehandler.rb:242:in `service'
	/Users/kai/.gem/ruby/3.1.3/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
	/Users/kai/.gem/ruby/3.1.3/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
	/Users/kai/.gem/ruby/3.1.3/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'

想问一下这该如何修改？

**Comment by nancheng58** [comment]
我遇到了一样的问题，请问你解决了吗?

**Comment by whu-lyh** [comment]
I met the same problem, and I made it solved by the following commands
```
bundle update
run run_server.sh
```

**Comment by Meiye-lj** [comment]
bundle update is not working

**Comment by mmhzheng** [comment]
the same problem

**Comment by mmhzheng** [comment]
The same problem
I find a [solution](https://github.com/jekyll/jekyll/issues/9451#issuecomment-1756467459) here.

**You should use jekyll serve -l (short for jekyll serve --livereload) instead.**  in `run_server.sh`

This is because:
jekyll liveserve was added by a now-unmaintained Jekyll plugin ("Hawkins"), but the functionality got merged into Jekyll https://github.com/jekyll/jekyll/pull/5142.

**Comment by taokz** [comment]
@mmhzheng  Thanks!

**Comment by GitYesm** [comment]
> jekyll serve -l

Thanks，the issue was successfully resolved!
