### ISSUE TITLE
导航栏_data/navigation.yml配置之后，点击404

### ISSUE THREAD

**Issue by kailinjiang** [RayeRen/acad-homepage.github.io#76]
<img width="605" alt="f25da7428dedad619bbd931397929a2" src="https://github.com/RayeRen/acad-homepage.github.io/assets/147908634/751fd304-a531-4e45-b53e-40e02f5836e1">
<img width="414" alt="f15f4d5cc73602c5aafaf2276a56d33" src="https://github.com/RayeRen/acad-homepage.github.io/assets/147908634/d43d7872-bef1-4b9f-9798-7fdd872d1301">

**Comment by shihuihong214** [comment]
您好，请问您后面如何解决的这个问题
