### ISSUE TITLE
谷歌学术爬虫Action报错

### ISSUE THREAD

**Issue by S-Kee** [RayeRen/acad-homepage.github.io#9]
![image](https://user-images.githubusercontent.com/21167731/168949924-8396831b-6d86-4684-9d70-eefdb2a98af6.png)

可能和我修改过仓库的名称有关，现在不知道怎么运行了

**Comment by S-Kee** [comment]
确实是因为中途修改过仓库名导致的，重新部署一遍就好了。

**Comment by YuMJie** [comment]
我也遇到同样的错误，但是我没有修改过仓库名，请问你是怎么解决的

**Comment by tangjyan** [comment]
> 我也遇到同样的错误，但是我没有修改过仓库名，请问你是怎么解决的

我是删库，重新弄了一遍就好了

**Comment by YuMJie** [comment]
> > 我也遇到同样的错误，但是我没有修改过仓库名，请问你是怎么解决的
> 
> 我是删库，重新弄了一遍就好了

![image](https://user-images.githubusercontent.com/64304120/222154350-8f8dac20-8e9c-469c-a262-12644204d20d.png)
我是报这样的错，请问你是怎么删除的

**Comment by yz-qiang** [comment]
你好，我重新部署了，还是显示Run failed: Get Citation Data。请问哪里还有小坑需要改的。
目前只是进行了如下操作。 感谢 感谢
![image](https://github.com/RayeRen/acad-homepage.github.io/assets/72866861/216ac0c7-d828-4dad-8823-0753f8dc0bc2)

**Comment by jialiangZ** [comment]
> 你好，我重新部署了，还是显示Run failed： Get Citation Data。请问哪里还有小坑需要改的。 目前只是进行了如下作。感谢 感谢 ![image](https://github.com/RayeRen/acad-homepage.github.io/assets/72866861/216ac0c7-d828-4dad-8823-0753f8dc0bc2)

请问您解决了吗
